export const ROUTES = {
  root: '/',
  auth: '/auth',
  authLogin: '/auth/login',
  authSignup: '/auth/signup',
  home: '/home',
  timeline: '/timeline',
  profile: '/profile',
  subscription: '/profile/subscription',
  calendar: '/profile/calendar',
  favorites: '/profile/favorites',
  privacy: '/profile/privacy',
  blog: '/blog',
  premium: '/premium',
  journey: '/journey',
  journeyView: '/journey/view',
  camera: '/camera',
  record: '/record',
} as const;
