export const ROUTES = {
  root: '/',
  auth: '/auth',
  authLogin: '/auth/login',
  authSignup: '/auth/signup',
  authCallback: '/auth/callback',
  home: '/home',
  timeline: '/timeline',
  profile: '/profile',
  profileEdit: '/profile/edit',
  subscription: '/profile/subscription',
  calendar: '/profile/calendar',
  favorites: '/profile/favorites',
  privacy: '/profile/privacy',
  blog: '/blog',
  blogCreate: '/blog/create',
  premium: '/premium',
  // 토스 빌링 인증 후 리다이렉트되는 착지 라우트 (successUrl/failUrl 오리진 뒤 경로)
  premiumBillingSuccess: '/premium/billing/success',
  premiumBillingFail: '/premium/billing/fail',
  journey: '/journey',
  journeyView: '/journey/view',
  camera: '/camera',
} as const;
